version: "3.8"
services:
  registro:
    build: .
    container_name: microservicio-registro
    ports:
      - "5001:5000"
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: registrodb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data:
